---
abstract: 'Perl modules for RFXCOM RF receivers/transmitters with AnyEvent'
author:
  - 'Mark Hindess <soft-cpan@temporalanomaly.com>'
build_requires:
  AnyEvent::MockTCPServer: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: AnyEvent-RFXCOM
requires:
  AnyEvent: '5.271'
  AnyEvent::Handle: '0'
  AnyEvent::Socket: '0'
  Carp: '0'
  Device::RFXCOM::Base: '1.103250'
  Device::RFXCOM::RX: '0'
  Device::RFXCOM::TX: '0'
  Device::W800: '0'
  Scalar::Util: '0'
  Sub::Name: '0'
  base: '0'
  constant: '0'
  perl: '5.008'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/beanz/anyevent-rfxcom-perl/issues
  homepage: http://search.cpan.org/dist/AnyEvent-RFXCOM/
  repository: git://github.com/beanz/anyevent-rfxcom-perl.git
version: '1.142230'
